quarkus:
  datasource:
    db-kind: "postgresql"
  hibernate-orm:
    database:
      generation: none
  # see https://quarkus.io/guides/flyway
  flyway:
    enabled: true
    table: "user_schema_history"
    clean-disabled: true
    baseline-version: "0.0.1"
    baseline-at-start: true
    migrate-at-start: true

  # see https://quarkus.io/guides/openapi-swaggerui
  smallrye-openapi:
    store-schema-directory: "target/openapi"
    store-schema-file-name: "user-service.yaml"
  swagger-ui:
    always-include: true
    path: "/docs"
    query-config-enabled: true

  # see https://quarkus.io/guides/container-image#customizing
  container-image:
    group: "AAU-ASE24W-group-E"

  mailer:
    from: "noreply@crowdlibrary.com"
    host: "localhost"
    port: 1025
    tls: false

smallrye:
  jwt:
    sign:
      key:
        location: "classpath:private.pem"
    verify:
      issuer: "user-service"
      key:
        location: "classpath:public.pem"

mp:
  messaging:
    outgoing:
      user:
        connector: "smallrye-kafka"
        topic: "cl.user"
        key:
          serializer: org.apache.kafka.common.serialization.UUIDSerializer
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer

"%prod":
  kafka:
    bootstrap:
      servers: "kafka:9092"

"%test":
  quarkus:
    datasource:
      devservices:
        enabled: true
        reuse: false
      # uncomment to test with local database instead of devservices
    #      username: "crowd-library"
    #      password: "crowd-library"
    #      jdbc:
    #        url: "jdbc:postgresql://localhost:5432/crowd-library"
    hibernate-orm:
      database:
        generation: drop-and-create
    flyway:
      # in %test we drop-and-create the database, thus, migration is neither needed nor possible
      migrate-at-start: false
  smallrye:
    jwt:
      sign:
        key:
          location: "src/main/resources/private.pem"
      verify:
        issuer: "user-service"
        key:
          location: "src/main/resources/public.pem"
  mp:
    messaging:
      outgoing:
        user:
          connector: "smallrye-in-memory"

"%dev":
  quarkus:
    datasource:
      devservices:
        enabled: true
        reuse: false
    hibernate-orm:
      database:
        generation: drop-and-create
    mailer:
      from: "dev@crowdlibrary.com"
      host: "localhost"
      port: 1025
      tls: false
  smallrye:
    jwt:
      sign:
        key:
          location: "src/main/resources/private.pem"
      verify:
        issuer: "user-service"
        key:
          location: "src/main/resources/public.pem"
