
quarkus:
  datasource:
    db-kind: "postgresql"

  hibernate-orm:
    database:
      generation: none

"%test":
  quarkus:
    datasource:
      devservices:
        enabled: true
        reuse: false
    hibernate-orm:
      database:
        generation: drop-and-create

"%dev":
  quarkus:
    datasource:
      devservices:
        enabled: true
        reuse: false
    hibernate-orm:
      database:
        generation: drop-and-create
