quarkus:
  datasource:
    db-kind: "postgresql"

  hibernate-orm:
    database:
      generation: none

  smallrye-jwt:
    issuer: "user-service"
    signer:
      privatekey:
        location: "classpath:private_key.txt"
      algorithm: RS256
    publickey:
      location: "classpath:public_key.txt"

"%test":
  quarkus:
    datasource:
      devservices:
        enabled: true
        reuse: false
    hibernate-orm:
      database:
        generation: drop-and-create
    smallrye-jwt:
      issuer: "user-service"
      signer:
        privatekey:
          location: "classpath:private_key.txt"
      publickey:
        location: "classpath:public_key.txt"

"%dev":
  quarkus:
    datasource:
      devservices:
        enabled: true
        reuse: false
    hibernate-orm:
      database:
        generation: drop-and-create
    smallrye-jwt:
      issuer: "user-service"
      signer:
        privatekey:
          location: "classpath:private_key.txt"
      publickey:
        location: "classpath:public_key.txt"
