
quarkus:
  datasource:
    db-kind: "postgresql"

  hibernate-orm:
    database:
      generation: none

"%test":
  quarkus:
    datasource:
      devservices:
        enabled: true
        reuse: false
    hibernate-orm:
      database:
        generation: drop-and-create

"%dev":
  quarkus:
    datasource:
      devservices:
        enabled: true
        reuse: true
        username: "crowd-library"
        password: "crowd-library"
        jdbc:
          url: "jdbc:postgresql://localhost:5432/crowd-library"
      hibernate-orm:
        database:
          generation: drop-and-create
