quarkus:
  datasource:
    db-kind: "postgresql"
  hibernate-orm:
    database:
      generation: none
smallrye:
  jwt:
    sign:
      key:
        location: "src/main/resources/private.pem"
    verify:
      key:
        location: "src/main/resources/public.pem"

"%test":
  quarkus:
    datasource:
      devservices:
        enabled: true
        reuse: false
    hibernate-orm:
      database:
        generation: drop-and-create
  smallrye:
    jwt:
      sign:
        key:
          location: "src/main/resources/private.pem"
      verify:
        key:
          location: "src/main/resources/public.pem"

"%dev":
  quarkus:
    datasource:
      devservices:
        enabled: true
        reuse: false
    hibernate-orm:
      database:
        generation: drop-and-create
  smallrye:
    jwt:
      sign:
        key:
          location: "src/main/resources/private.pem"
      verify:
        key:
          location: "src/main/resources/public.pem"

