
quarkus:
  datasource:
    db-kind: "postgresql"

  hibernate-orm:
    database:
      generation: none
  http:
    auth:
      basic: true

"%test":
  quarkus:
    datasource:
      devservices:
        enabled: true
        reuse: false
    hibernate-orm:
      database:
        generation: drop-and-create
    http:
      auth:
        basic: true

"%dev":
  quarkus:
    datasource:
      devservices:
        enabled: true
        reuse: false
    hibernate-orm:
      database:
        generation: drop-and-create
    http:
      auth:
        basic: true
